### ISSUE TITLE
Basic analytics

### ISSUE THREAD

**Issue by kcjpop** [kcjpop/vd#10]
### What

We need to count pageview of words for analytics purposes. Should be on daily basis, e.g.

| date       | word   | action | count |
| ---------- | ------- | -------- | -------- |
| 2022-03-23 | abandon | pageview | 3        |
| 2022-03-24 | abandon | pageview | 4        |
| 2022-03-25 | abandon | pageview | 9        |
| 2022-03-25 | address | pageview |  9        |

Would be useful for features like **Most viewed words of the day**, or we can do SSR for most popular words.

Worth to read https://css-tricks.com/send-an-http-request-on-page-exit/. tldr: use `navigator.sendBeacon`

**Comment by DangMin** [comment]
cái này  anh có record vào db không?

**Comment by kcjpop** [comment]
Có nhưng anh chưa biết nên bỏ vào db nào 🤔

**Comment by kcjpop** [comment]
Too much effort, let's use Plausible https://plausible.io/

**Comment by DangMin** [comment]
oh well, I did try to do it with supabase already
