### ISSUE TITLE
Hide speaker icon if voice isn't ready yet

### ISSUE THREAD

**Issue by kcjpop** [kcjpop/vd#11]
In `Speech.jsx` we should hide voice icon if selected voice isn't yet available.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/172503/159941039-23db6a51-2516-4e24-8087-2fed9f5c6ae2.png">

This can be done by moving this finding voice code block into a `useEffect`
https://github.com/kcjpop/vd/blob/3f425e8c733e8234047b7637f6f3b1a798de69c5/web/lib/word/Speech.jsx#L7-L23

**Comment by DangMin** [comment]
assign cho ai đây anh 😄

**Comment by kcjpop** [comment]
@DangMin  Thích thì cứ lấy làm thôi 😄
