### ISSUE TITLE
Add pronunciation

### ISSUE THREAD

**Issue by kcjpop** [kcjpop/vd#6]
Use Web Speech API to provide sample pronunciation.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API#speech_synthesis

Demo: https://mdn.github.io/web-speech-api/speak-easy-synthesis/

**Comment by DangMin** [comment]
này chắc parser merged rồi e mới làm nhỉ 🤔

**Comment by kcjpop** [comment]
Làm trong https://github.com/kcjpop/vd/pull/7 rồi 😄
